workflows:
  nodejs_tests:
    name: Run Node.js tests
    instance_type: linux_x2
    environment:
      node: latest
      vars:
        NODEJS_PROJECT_DIR: "."
    scripts:
      - name: Check OS
        script: uname -a
      - name: Install dependencies
        script: |
          cd $NODEJS_PROJECT_DIR
          npm install
      - name: Run lint
        script: |
          cd $NODEJS_PROJECT_DIR
          npm run lint
      - name: Run tests
        script: |
          cd $NODEJS_PROJECT_DIR
          npm run test
    cache:
      cache_paths:
        - ~/.npm
        - $NODEJS_PROJECT_DIR/node_modules
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
        - pattern: "*"
          include: true
          source: false
